# cfg file for configuring connector test drivers
test_arguments:
  lr: "0.01"
  epoch: "30"
  batch_size: "8"
  model_name: "resnet50"
  accruacy_lower_bound: "50"
  accruacy_upper_bound: "99"
  sensitivity_lower_bound: "0.5"
  sensitivity_upper_bound: "1.0"
  specificity_lower_bound: "0.0"
  specificity_upper_bound: "0.5"
  train_data_size: "10"
  cnvrg_dataset: "none"
  file_dir: "test.csv"
  file_dir: "sample_dataset/DailyDelhiClimateMissing.csv"